version: '3'
services:
  think-prompt-ass1:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - ./logs:/app/logs
      - ./input:/app/input
    networks:
      - recsys-network

networks:
  recsys-network:
    name: recsys-network